[build]
  publish = "public"
  command = "npm run build"
  ignore = "exit 0" 
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"

