mainNavigation:
  - label: Buch kaufen
    url: https://amreis.de/ha118
  - label: Rock'n'Roll
    url: /tag/musik
    children:
      - { url: /tag/interview, label: Interview }
      - { url: /tag/bands-und-reviews, label: Bands & Reviews }
      - { url: /tag/konzerte, label: Konzerte }
      - { url: /tag/festivals, label: Festivals }
      - { url: /tag/buecher-und-filme, label: Bücher & Filme }
  - label: Vegan
    url: /tag/vegan
    children:
      - { url: /tag/rezepte, label: Vegane Rezepte }
      - { url: /tag/go-vegan, label: Darum vegan }
      - { url: /tag/vegane-lokale, label: Vegane Lokale }
      - { url: /tag/vegan-beauty, label: Mode & Beauty vegan }
      - { url: /tag/produkte, label: Vegane Produkte }
  - label: Gesellschaft
    url: /tag/gesellschaft
    children:
      - { url: /tag/tierrechte, label: Tierrechte }
      - { url: /tag/klima-umweltschutz, label: Klima & Umweltschutz }
      - { url: /tag/politik-soziales, label: Politik & Soziales }
      - { url: /tag/kunst, label: Kunst }
  - label: Unterwegs
    url: /tag/unterwegs
    children:
      - { url: /tag/reisen, label: Reisen }
      - { url: /tag/hamburg, label: Hamburg }
      - { url: /tag/ausflug, label: Ausflug }
      - { url: /tag/skandinavien, label: Skandinavien }
      - { url: /tag/england, label: Britische Inseln }
  - label: Kreatives
    url: /tag/kreatives
    children:
      - { url: /tag/diy, label: DIY }
      - { url: /tag/prosa, label: Prosa }
      - { url: /tag/lyrik, label: Lyrik }
      - { url: /tag/tagebuch, label: Tagebuch }
